[features]
seeds = false
skip-lint = false

[programs.localnet]
hot_potato = "FTmU5btw8kipZEcacr1cf5kd7Ld9qnaBmQjxbyYd76yo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
gameMasterClient = "yarn run ts-node client/gameMaster.ts"
playerClient = "yarn run ts-node client/player.ts"
checkClient = "yarn run ts-node client/check.ts"
playgroundClient = "yarn run ts-node client/playground.ts"
