import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WalletContext } from "./walletContext";
import Header from "./header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WalletContext>
          <Header />
          {children}
        </WalletContext>
      </body>
    </html>
  );
}
